services:

  # keycloak:
  #   image: quay.io/keycloak/keycloak:26.0
  #   ports:
  #     - 9999:9999
  #   restart: always
  #   environment:
  #     KC_HOSTNAME: localhost
  #     KC_HOSTNAME_PORT: 9999
  #     KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
  #     KEYCLOAK_ADMIN: admin
  #     KEYCLOAK_ADMIN_PASSWORD: admin
  #     KC_HEALTH_ENABLED: "true"
  #     KC_LOG_LEVEL: info
  #   networks:
  #     - my-network

  mysql:
    image: mysql:8.0.30
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: todaii
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: bqt020402
      MYSQL_PASSWORD: bqt020402
    volumes:
      - mysql:/var/lib/mysql

    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mysql: